In [1]:
import pandas as pd


data = pd.read_csv("indoc.csv")
data.head(10)
data.shape

(1200, 5)

In [2]:
docs = data["Document"]

In [3]:

cl = [xs.replace('ইহাতে মন্তব্য প্রদান বন্ধ রয়েছে                                |    ', '') for xs in docs]
cl2 = [xs.replace('\xa0', '').replace('\u200c', '') for xs in cl]
cl3 = [xs.replace('?', u'।').replace('!', u'।').replace(';', u'।') for xs in cl]

sentTok =[]
wordTok = []
for doc in cl3:
    sentTok.append(doc.split('।'))
sentTok[0]

['স্নাতক পাস আবুল হাশেম (৩০) ও তাঁর ভাই উচ্চমাধ্যমিক পাস সুজন হোসেন (২৩) একসময় ঢাকায় গার্মেন্টসে চাকরি করতেন',
 ' তাঁদের আরেক ভাই অষ্টম শ্রেণি পাস ফরহাদ হোসেন (২৫) আগে নোয়াখালীতে গ্রামের বাড়িতে কৃষিকাজ করতেন',
 ' এখন তিন ভাইই পরিবার নিয়ে ঢাকার উত্তরার বহুতল ভবনে বাস করেন',
 ' ভাড়া দেন ৫০ হাজার টাকা',
 ' গত শনিবার তিন ভাইয়ের দুজন সুজন ও ফরহাদকে ২০ হাজার পিছ ইয়াবাসহ উত্তরার সেই ফ্ল্যাট থেকে গ্রেপ্তার করেছে ঢাকা মহানগর গোয়েন্দা পুলিশ (ডিবি)',
 ' এই ইয়াবার আনুমানিক মূল্য ৩০ লাখ টাকা',
 ' আর তিন ভাইয়ের ফ্ল্যাট থেকে জব্দ করা হয়েছে আরও নগদ ২ লাখ ৫৭ হাজার টাকা',
 ' রোববার সুজন ও ফরহাদকে ঢাকার আদালতে হাজির করে ডিবি এক প্রতিবেদন দিয়ে বলছে, হাশেম, সুজন ও ফরহাদ তিন ভাই কয়েক বছর ধরে কক্সবাজার থেকে ইয়াবার চালান ঢাকায় এনে জমজমাট ব্যবসা করছেন',
 ' তাঁদের সঙ্গে কারা জড়িত, তা খুঁজে বের করতে দুই ভাইকে তিন দিন জিজ্ঞাসাবাদের অনুমতি দিয়েছেন আদালত',
 ' তিনজনের বাবা ছিলেন হকারমাদক ব্যবসার অভিযোগ থাকা এই তিনজনের বাবার নাম বিল্লাল হোসেন',
 ' তাঁর গ্রামের বাড়ি নোয়াখালী',
 ' অনেক আগে থেকে তিনি ঢাকায় থাকেন',
 ' রা

In [4]:


import re
pnList = ['.', ',', ':', '(', ')', '[', ']', '{', '}', '`', '*', '&', '‘', '’', '–']
cl4 = [xs.replace(u'।'," ") for xs in cl3]

cl5=[[] for x in range(len(cl4))]
for i in range(len(cl4)):
#     cl5[i] = cl4[i].replace("(","").replace(")","").replace(",","").replace("+","").replace(")","")
    cl5[i] = re.sub("[০১২৩৪৫৬৭৮৯]",'',cl4[i])
    cl5[i] = re.sub("[,./<>)(}{_*&^%$#@~`]",'',cl5[i])

for doc in cl5:
    wordTok.append(doc.split())


#remove stopword
stRem = [[] for i in range(len(wordTok))]

def remStWords(punctuF):
    stWord = open("./stopwords-bn.txt", encoding='utf8')
    stWordFile = [i.rstrip() for i in stWord]
    filtStWord = [w for w in punctuF if w not in stWordFile]

    return filtStWord
for i in range(len(wordTok)):
    stRem[i] = remStWords(wordTok[i])
    

print(stRem[1])
print(len(stRem))
allWord = []
for i in range(len(stRem)):
    allWord+=stRem[i]
 


print(len(allWord))

['ঢাকার', 'কামরাঙ্গীরচরের', 'নবাবচরে', 'বুড়িগঙ্গা', 'নদী', 'দখল', 'স্থায়ী', 'রূপ', 'নিচ্ছে', 'নদীর', 'সীমানা', 'নির্ধারণ', 'বিষয়ে', 'জেলা', 'প্রশাসনের', 'প্রতিবেদনের', 'কারণে', 'অবস্থার', 'সৃষ্টি', 'রয়েছে', 'প্রভাবশালী', 'ব্যক্তিদের', 'চাপ', 'অভ্যন্তরীণ', 'নৌপরিবহন', 'কর্তৃপক্ষের', 'বিআইডব্লিউটিএ', 'উদ্যোগের', 'অভাব', 'বিআইডব্লিউটিএ', 'জেলা', 'প্রশাসন', 'সূত্রে', 'নৌপরিবহনমন্ত্রী', 'শাজাহান', 'খান', 'গত', 'বছরের', 'এপ্রিলে', 'বুড়িগঙ্গার', 'কামরাঙ্গীরচর', 'এলাকা', 'পরিদর্শন', 'সময়', 'নদীর', 'জায়গায়', 'অবৈধ', 'স্থাপনা', 'গড়ে', 'উঠেছে', 'সেগুলো', 'ভাঙার', 'ঘোষণা', 'এরপর', 'জুলাই', 'বিআইডব্লিউটিএ', 'অভিযান', 'চালিয়ে', 'তিনটি', 'স্থাপনার', 'বাইরের', 'দেয়ালের', 'সামান্য', 'অংশ', 'ভেঙে', 'দেয়', 'সাংসদ', 'হাজি', 'সেলিমের', 'মালিকানাধীন', 'স্থাপনার', 'সীমানাদেয়াল', 'ভাঙা', 'এরপরই', 'নবাবচরে', 'নদীতীরের', 'ভবনমালিকেরা', 'জেলা', 'প্রশাসনের', 'সীমানা', 'নির্ধারণের', 'আবেদন', 'জানালে', 'কমিটি', 'কমিটি', 'সিএস', 'ক্যাডেস্টাইল', 'সার্ভে', 'আরএস', 'রিভাইস', 'সার্ভে', 'রেকর্ড', 'অনুযায়ী', 'নদীর', 'সীমা

In [5]:
import pickle as pk
inp = open('F:\dataP\\tfidfSorted','rb')

tfidfSorted = pk.load(inp)
inp.close()


In [6]:
import random
import numpy as np
from sklearn.metrics import f1_score
#Import model for NB
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split 
from sklearn import tree
from sklearn.metrics import accuracy_score
from sklearn import svm
from sklearn import preprocessing
import itertools
tfIdfSorted = dict(itertools.islice(tfidfSorted.items(),6000))

# create classifier object gor model
model=GaussianNB()


In [7]:
key = pd.read_csv("F:\\dataP\\keyF6k.csv")
key.head(5)
len(stRem)


1200

In [8]:
keyF = list(key['key'])
tfIdfFl = [[] for i in range(len(stRem))] 
for i in range(len(stRem)):
    for word in keyF:
        if word in stRem[i]:
            tfIdfFl[i].append(tfIdfSorted[word])
        else:
            tfIdfFl[i].append(0)

In [9]:
len(tfIdfFl[0])

3043

In [10]:
from sklearn.model_selection import train_test_split 

from sklearn import svm
from sklearn import preprocessing


dataX = tfIdfFl
dataY = data['class']
print(len(dataX))

trainX, testX, trainY, testY = train_test_split(dataX, dataY, test_size = 0.20, random_state = 0,stratify=dataY)

1200


In [43]:
# trainX = dataX[:960]
# trainY = dataY[:960]

# testX = dataX[460:]
# testY = dataY[460:]

In [11]:

#Import model for NB
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=GaussianNB()

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using NB :',accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using NB :',accuracy_score(testY, predictions_test))


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using NB : 0.9947916666666666

Test Accuracy using NB : 0.8541666666666666

Confusion matrix:
 [[156   1   0   3   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  1   0   0 159   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       0.99      0.97      0.98       160
['আন্তর্জাতিক']       0.99      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       0.98      0.99      0.99       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           0.99       960
      macro avg       0.99      0.99      0.99       960
   weighted avg       0.99      0.99      0.99       960


Confusion matrix:
 [[36  0  0  3  1  0]
 [12 25  0  1  1  1]
 [ 1  0 39  0  0  0]
 [ 4  0  0 36  0  0]
 [ 3  0  0  6 31  0]
 [ 2  0  0  0  0 38]]
   

In [12]:

#Import model for NB
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=svm.SVC(kernel='linear', C=.5)

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using NB :',accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using NB :',accuracy_score(testY, predictions_test))


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using NB : 1.0

Test Accuracy using NB : 0.8208333333333333

Confusion matrix:
 [[160   0   0   0   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  0   0   0 160   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       1.00      1.00      1.00       160
['আন্তর্জাতিক']       1.00      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       1.00      1.00      1.00       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           1.00       960
      macro avg       1.00      1.00      1.00       960
   weighted avg       1.00      1.00      1.00       960


Confusion matrix:
 [[28  5  1  3  2  1]
 [ 3 31  1  3  2  0]
 [ 1  0 38  0  0  1]
 [ 5  0  0 33  0  2]
 [ 5  0  1  2 32  0]
 [ 1  2  0  2  0 35]]
                 p

In [30]:
from sklearn.tree import DecisionTreeClassifier
#Import model for NB
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=DecisionTreeClassifier()

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using DT : %f'%accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using DT :',accuracy_score(testY, predictions_test))


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using DT : 1.000000

Test Accuracy using DT : 0.7166666666666667

Confusion matrix:
 [[160   0   0   0   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  0   0   0 160   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       1.00      1.00      1.00       160
['আন্তর্জাতিক']       1.00      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       1.00      1.00      1.00       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           1.00       960
      macro avg       1.00      1.00      1.00       960
   weighted avg       1.00      1.00      1.00       960


Confusion matrix:
 [[29  3  1  2  3  2]
 [ 3 23  5  2  5  2]
 [ 4  1 29  1  3  2]
 [ 2  4  2 30  2  0]
 [ 2  2  2  1 33  0]
 [ 2  5  0  1  4 28]]
             