In [1]:
import pandas as pd


data = pd.read_csv("indoc.csv")
data.to_csv("F:\dataP\indoc.csv",encoding='utf-8-sig',mode='w')

In [15]:
import pickle as pk
inp = open('F:\dataP\\tfidfftotal30k','rb')

tfidf = pk.load(inp)
inp.close()
print(len(tfidf[0]))



30000


In [16]:
from sklearn.model_selection import train_test_split 

from sklearn import svm
from sklearn import preprocessing
from sklearn.tree import DecisionTreeClassifier


dataX = tfidf
dataY = data['class']


trainX, testX, trainY, testY = train_test_split(dataX, dataY, test_size = 0.2, random_state = 0,stratify=dataY)

In [5]:
print(len(testY))

240


In [18]:

#Import model for NB
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=GaussianNB()

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using NB :',accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using NB :',accuracy_score(testY, predictions_test))

from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
 
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using NB : 1.0

Test Accuracy using NB : 0.7583333333333333

Confusion matrix:
 [[160   0   0   0   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  0   0   0 160   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       1.00      1.00      1.00       160
['আন্তর্জাতিক']       1.00      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       1.00      1.00      1.00       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           1.00       960
      macro avg       1.00      1.00      1.00       960
   weighted avg       1.00      1.00      1.00       960


Confusion matrix:
 [[32  0  0  8  0  0]
 [14 19  0  4  3  0]
 [ 1  0 39  0  0  0]
 [ 2  0  0 37  0  1]
 [10  0  0  6 23  1]
 [ 3  1  0  4  0 32]]
                 p

In [19]:

#Import model for NB
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=DecisionTreeClassifier()

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using DT :',accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using DT :',accuracy_score(testY, predictions_test))


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using DT : 1.0

Test Accuracy using DT : 0.7583333333333333

Confusion matrix:
 [[160   0   0   0   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  0   0   0 160   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       1.00      1.00      1.00       160
['আন্তর্জাতিক']       1.00      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       1.00      1.00      1.00       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           1.00       960
      macro avg       1.00      1.00      1.00       960
   weighted avg       1.00      1.00      1.00       960


Confusion matrix:
 [[26  3  0  5  4  2]
 [ 2 28  4  2  3  1]
 [ 1  1 35  2  1  0]
 [ 0  2  3 32  0  3]
 [ 2  1  2  2 32  1]
 [ 1  1  2  6  1 29]]
                 p

In [22]:

#Import model for NB
from sklearn.naive_bayes import GaussianNB,MultinomialNB
from sklearn.metrics import accuracy_score
# create classifier object gor model
model=svm.SVC(kernel='linear')

# train the model with fit function
model.fit(trainX, trainY)
   
# make predictions on training data
predictions_train = model.predict(trainX)
print('\nTraining Accuracy using SVM :',accuracy_score(trainY, predictions_train))

# make predictions on test data
predictions_test = model.predict(testX)
print('\nTest Accuracy using SVM :',accuracy_score(testY, predictions_test))


from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
print('\nConfusion matrix:\n',confusion_matrix(trainY,predictions_train))
print(classification_report(trainY,predictions_train))  

print('\nConfusion matrix:\n',confusion_matrix(testY,predictions_test))
print(classification_report(testY,predictions_test)) 



Training Accuracy using SVM : 1.0

Test Accuracy using SVM : 0.8708333333333333

Confusion matrix:
 [[160   0   0   0   0   0]
 [  0 160   0   0   0   0]
 [  0   0 160   0   0   0]
 [  0   0   0 160   0   0]
 [  0   0   0   0 160   0]
 [  0   0   0   0   0 160]]
                 precision    recall  f1-score   support

           ['']       1.00      1.00      1.00       160
['আন্তর্জাতিক']       1.00      1.00      1.00       160
       ['খেলা']       1.00      1.00      1.00       160
  ['দূর পরবাস']       1.00      1.00      1.00       160
   ['বাংলাদেশ']       1.00      1.00      1.00       160
     ['বিনোদন']       1.00      1.00      1.00       160

       accuracy                           1.00       960
      macro avg       1.00      1.00      1.00       960
   weighted avg       1.00      1.00      1.00       960


Confusion matrix:
 [[31  2  0  3  4  0]
 [ 3 33  0  1  2  1]
 [ 2  0 38  0  0  0]
 [ 2  1  0 36  0  1]
 [ 2  0  1  2 34  1]
 [ 0  2  0  1  0 37]]
                